### ISSUE TITLE
Limited Support for Json Path Filter

### ISSUE THREAD

**Issue by alc0der** [Leopard2A5/fhttp#52]
I believe this comes from the usage of `jsonpath_lib`. There are cases where it is not possible to filter an array based on an array within it.

example:
```json
{
  "store": {
    "book": [
      {
        "category": "reference",
        "author": ["Nigel Rees"],
        "title": "Sayings of the Century",
        "price": 8.95
      }
    ],
    "bicycle": {
      "color": "red",
      "price": 19.95
    }
  },
  "expensive": 10
}
```

json path: `$.store.book[?(@.author[0] == "Nigel Rees")]`

I have tried other operators such as `in`, `contains`, but it seems like they are not supported.

The errors are consistent with https://freestrings.github.io/jsonpath/

I have managed to find a workaround by using Deno

Something like:
```javascript
let book = JSON.parse(body).find(b => b.author.includes("Nigel Rees"))
print(book)
setResult(book)
```

**Comment by Leopard2A5** [comment]
Hi!

Indeed that error must come from the jsonpath library.
I'll update to the latest version but don't know if that will fix the error.

**Comment by Leopard2A5** [comment]
Updating to the latest version doesn't seem to help.
However, initial tests with the [jsonpath-rust](https://crates.io/crates/jsonpath-rust) crate seem to get your query to work (albeit with single quotes and not double quotes).

I'll see if i can swap out jsonpath_lib for jsonpath-rust, as it seems to have advantages

**Comment by alc0der** [comment]
Thank you. Also you could consider [JMESpath](https://jmespath.org) in case non of the JSON Path libraries turn out satisfactory.

**Comment by Leopard2A5** [comment]
Okay, sooo:

jsonpath-rust has an issue in that it always returns a Vec<&Value> which is problematic because fhttp can't know if it should expect a single result or an array of them. If i just replace jsonpath-lib with jsonpath-rust I'd be breaking existing behavior and thus existing request definitions. I've asked about this here: https://github.com/besok/jsonpath-rust/issues/3

I had a look at jmespath and it looked promising until i added a dependency to it. It seems to be outdated because it's throwing a compiler error in its own integration of serde_json. Also the code is 2 years old.

Right now, honestly, I'd let the issue rest, given that deno is a suitable replacement. It's frustrating though!
